name: Nightly

on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  core:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSTLBFGS_UNIT_TESTS=ON

    - name: CMake Build
      run: cmake --build build --parallel

    - name: CTest
      run: ctest --test-dir build -V


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -DSTLBFGS_UNIT_TESTS=ON

    - name: Release build
      run: cmake --build build --parallel --config Release

    - name: Release CTest
      run: ctest --test-dir build -C Release -V

    - name: Debug build
      run: cmake --build build --parallel --config Debug

    - name: Debug CTest
      run: ctest --test-dir build -C Debug -V
